#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x
set -o allexport
source "/swarmlet-config"

main() {
  [[ -f /security.htpasswd ]] && rm /security.htpasswd
  echo $SWARMLET_REGISTRY_PASSWORD | htpasswd -ciB /security.htpasswd $SWARMLET_REGISTRY_USERNAME
}

main "$@"
