#!/usr/bin/env bash

set -eo pipefail
[[ $DEBUG ]] && set -x
set -o allexport

main() {
  tail -f /dev/null
}

validate() {
  declare cmd="validate"
  [[ "$1" == "$cmd" ]] && shift 1

  yq v "$1"
}

"$@"
