#!/usr/bin/env bash

set -eo pipefail
[[ $DEBUG ]] && set -x

NAME=$(basename "$PWD")

main() {
  echo "$PREFIX Running $NAME entrypoint script"

  echo -e "Leader IP: $LEADER_IP"

  if [[ ! -d $TRAEFIK_CERTS ]]; then
    echo "$PREFIX Creating $TRAEFIK_CERTS/acme.json"
    mkdir -p "$TRAEFIK_CERTS"
    touch "$TRAEFIK_CERTS/acme.json"
    chmod 600 "$TRAEFIK_CERTS/acme.json"
  fi
}

main "$@"
