#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

cat << EOM
———————————————————————————————————————————————————————————————————————————————

        _______ _  _  _ _______  ______ _______        _______ _______
        |______ |  |  | |_____| |_____/ |  |  | |      |______    |   
        ______| |__|__| |     | |    \_ |  |  | |_____ |______    |    


       Description:  A small tool to manage swarm deployments,
                     load balancing, SSL, metrics and more.
       Version:      1.0 - 6ef0c484553656dc0b4b9cbd85b4d8d5a9e2586b
       Author:       Tjerk Woudsma <tjerk@passionatepeople.io>
       Website:      https://swarmlet.dev

———————————————————————————————————————————————————————————————————————————————
       Thank you for installing Swarmlet!
EOM

FPREFIX="=====>"
PREFIX="----->"
INDENT="      "

DEPENDENCIES=(git apt-transport-https moreutils apache2-utils)
REPOSITORY="https://github.com/woudsma/swarmlet.git"
SWARMLET_INSTALL_ROOT="/opt/swarmlet"

install() {
  echo "$FPREFIX Installing Swarmlet"

  echo "$PREFIX Installing dependencies"
  apt-get update -y -qq
  apt-get install -y -qq "${DEPENDENCIES[@]}"
  wget -nv -O - https://get.docker.com/ | sh
  curl -fsSL "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose

  echo "$PREFIX Cloning Swarmlet from $REPOSITORY"
  mkdir -p $SWARMLET_INSTALL_ROOT; cp -R $(dirname "$0")/* $SWARMLET_INSTALL_ROOT/
  # git clone -q $REPOSITORY $SWARMLET_INSTALL_ROOT

  echo "$PREFIX Linking executable"
  ln -s $SWARMLET_INSTALL_ROOT/swarmlet /usr/local/sbin/

  echo "$FPREFIX Initializing Swarmlet"
  swarmlet init "$@"

  echo "$FPREFIX Installation complete"
  # TODO: get from compose files and handle no domain
  DOMAIN=${DOMAIN:-\$DOMAIN}
  echo "$FPREFIX Stacks deployed and available at:"
  echo "[traefik]       https://traefik.$DOMAIN"
  echo "[swarmpit]      https://swarmpit.$DOMAIN"
  echo "[grafana]       https://grafana.$DOMAIN"
  echo "[consul]        https://consul.$DOMAIN"
  echo "[unsee]         https://unsee.$DOMAIN"
  echo "[prometheus]    https://prometheus.$DOMAIN"
  echo "[alertmanager]  https://alertmanager.$DOMAIN"
  echo
  echo "$PREFIX Please wait a minute or two for Traefik to initialize..."
  echo "$PREFIX Usage:"
  echo "$INDENT Create a repository on the swarm using:"
  echo -e "$INDENT $ swarmlet repo:create <name>\n"
}

install "$@"
