#!/usr/bin/env bash
# shellcheck disable=SC2034,SC1090,SC2143,SC2139

set -eo pipefail
[[ $DEBUG ]] && set -x
set -o allexport

FPREFIX="=====>"
PREFIX="----->"
INDENT="      "

if [[ "$SWARMLET_INSTALL" == "true" ]]; then
  SWARMLET_ROOT="$SWARMLET_INSTALL_ROOT"
else
  SWARMLET_ROOT="/mnt/gfs/swarmlet"
fi

source "$SWARMLET_ROOT/src/constants"
source "$SWARMLET_FUNCTIONS"
set +o allexport

COMMAND="$SWARMLET_ROOT/src/commands/$1"

if [[ -f "$COMMAND" ]]; then
  "$COMMAND" "$@"
elif [[ $(list-internal-functions | grep -w "$1") ]]; then
  "$@"
else
  echo "$PREFIX Unknown command: $1"
fi
