#!/usr/bin/env bash

set -eo pipefail
[[ $DEBUG ]] && set -x
set -o allexport

FPREFIX="=====>"
PREFIX="----->"
INDENT="      "

install() {
  echo "$FPREFIX Joining Swarmlet cluster"
  REMOTE_HOST="$1"

  echo "$PREFIX Adding swarm SSH key to authorized keys"
  mkdir -p ~/.ssh
  curl -fsSL "https://join.$REMOTE_HOST/ansible.pub" >~/.ssh/authorized_keys
  chmod 700 ~/.ssh

  echo "$PREFIX Calling back to manager"
  curl -fsSL "https://join.$REMOTE_HOST/callback"
}

install "$@"
