#!/usr/bin/env bash
# shellcheck disable=SC2143,SC2011,SC2068,SC2015,SC2139

set -eo pipefail
[[ $DEBUG ]] && set -x

init() {
  declare cmd="init"
  [[ "$1" == "$cmd" ]] && shift 1

  swarmlet() {
    "$SWARMLET_INSTALL_ROOT/swarmlet" "$@"
  }

  echo "$FPREFIX Print environment"
  printenv && true

  if [[ "$INSTALLATION_TYPE" == "interactive" ]]; then
    echo "$PREFIX Starting interactive installation"
    swarmlet dialog welcome
    swarmlet dialog auth-info

    declare -A INSTALL_OPTS
    OPTS_CONFIRMED="false"
    while [[ "$OPTS_CONFIRMED" == "false" ]]; do
      INSTALL_OPTS[SWARMLET_USERNAME]=$(swarmlet dialog set-username)
      INSTALL_OPTS[SWARMLET_PASSWORD]=$(swarmlet dialog set-password)
      INSTALL_OPTS[SSH_AUTHORIZED_KEYS]=$(swarmlet dialog set-ssh-authorized-keys)
      INSTALL_OPTS[NEW_HOSTNAME]=$(swarmlet dialog set-hostname)
      INSTALL_OPTS[ROOT_DOMAIN]=$(swarmlet dialog domain-config)
      INSTALL_OPTS[CA_SERVER]=$(swarmlet dialog ca-config)
      INSTALL_OPTS[INSTALL_MODULES]=$(swarmlet dialog install-modules)
      INSTALL_OPTS[CREATE_SWAP]=$(swarmlet dialog add-swap)
      INSTALL_OPTS[INSTALL_ZSH]=$(swarmlet dialog install-zsh)
      OPTS_CONFIRMED=$(swarmlet dialog confirm-install)
    done

    for KEY in "${!INSTALL_OPTS[@]}"; do
      export "$KEY=${INSTALL_OPTS[$KEY]}"
    done

    echo "$FPREFIX Configuration confirmed"
    echo "$PREFIX The installation will take a few minutes to complete"
  else
    echo "$PREFIX Starting noninteractive installation"
  fi

  install-ansible && true

  echo "$PREFIX Installing modules"

  # SWARMLET_MODULES=()
  # for MODULE in "$SWARMLET_MODULES_ROOT"/core/*; do
  #   SWARMLET_MODULES+=("core/$(basename "$MODULE")")
  # done

  # # TODO: refactor this mess
  # # INSTALL_MODULES must be in this format: (module1 module2), or "" to skip optional modules installation
  # for MODULE in $(echo "${INSTALL_MODULES[@]}" | sed -r "s/\(|\)//g"); do
  #   SWARMLET_MODULES+=("recommends/$(basename "$MODULE")")
  # done

  swarmlet stack deploy registry "$SWARMLET_MODULES_ROOT"/core
  swarmlet stack build deployer "$SWARMLET_MODULES_ROOT"/core
  swarmlet stack deploy deployer "$SWARMLET_MODULES_ROOT"/core

  for MODULE in ${SWARMLET_MODULES[@]}; do
    echo "$PREFIX Installing $MODULE"
    swarmlet repo create "$(basename "$(echo "$MODULE" | sed -r "s/\"//g")")" &>/dev/null
    git-local-push "$SWARMLET_MODULES_ROOT/$(echo "$MODULE" | sed -r "s/\"//g")" >/dev/null
  done
}

"$@"
