#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

FPREFIX="=====>"
PREFIX="----->"
INDENT="      "

NAME=$(basename $PWD)

main() {
  echo "$PREFIX Running $NAME entrypoint script"
  # echo "$PREFIX Environment:"; printenv
}

main "$@"
