#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

ls -al /
cat /swarmlet-config
for f in /run/secrets/*; do cat $f; done

# TODO: improve configuration workflow
set -o allexport
source "/opt/swarmlet/src/constants"
source "/swarmlet-config"

main() {
  echo "$PREFIX Starting deployment"
  echo "$INDENT Command: $@"
  "$@"
}

deploy() {
  declare cmd="deploy"
  [[ "$1" == "$cmd" ]] && shift 1

  REPO_PATH="$1"
  REPO_NAME=$(basename $REPO_PATH)
  ENV_FILE="$REPO_PATH/.env"
  ENTRYPOINT_FILE="$REPO_PATH/entrypoint"
  COMPOSE_FILE="$REPO_PATH/docker-compose.yml"

  if [[ -f $ENV_FILE ]]; then
    set -o allexport
    source $ENV_FILE
    set +o allexport
  fi

  if [[ -f $ENTRYPOINT_FILE && $REPO_NAME != "deployer" ]]; then
    source $ENTRYPOINT_FILE
  fi

  if [[ -f $COMPOSE_FILE ]]; then
    # TODO: only log in if build step is defined in docker-compose.yml
    echo "$PREFIX Logging into local registry"
    echo $SWARMLET_REGISTRY_PASSWORD | docker login --password-stdin \
      -u $SWARMLET_REGISTRY_USER \
      $SWARMLET_REGISTRY

    echo "$PREFIX Building $REPO_NAME"
    cd $REPO_PATH
    docker-compose build --parallel

    echo "$PREFIX Pushing $REPO_NAME"
    docker-compose push

    echo "$PREFIX Deploying $REPO_NAME"
    docker stack deploy --compose-file $COMPOSE_FILE $REPO_NAME

    HOSTS=$(docker-compose config | grep -o "Host:.*")
    DOMAINS="${HOSTS//Host:/}"
    PROTOCOL=https # TODO: detect exposed protocols

    echo "$FPREFIX Stack deployed:"
    for DOMAIN in ${DOMAINS[@]}; do echo "[$REPO_NAME] — $PROTOCOL://$DOMAIN"; done
    echo
  else
    echo "$PREFIX No docker-compose.yml found, exiting"
    exit 1
  fi
}

main "$@"
