#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

# TODO: improve configuration workflow
set -o allexport
source "/opt/swarmlet/src/config"

main() {
  echo "$PREFIX Starting deployment"
  echo "$INDENT Command: $@"
  "$@"
}

deploy() {
  declare cmd="deploy"
  [[ "$1" == "$cmd" ]] && shift 1

  REPO_PATH="$1"
  REPO_NAME=$(basename $REPO_PATH)
  ENV_FILE="$REPO_PATH/.env"
  ENTRYPOINT_FILE="$REPO_PATH/entrypoint"
  COMPOSE_FILE="$REPO_PATH/docker-compose.yml"

  if [[ -f $ENV_FILE ]]; then
    set -o allexport
    source $ENV_FILE
    set +o allexport
  fi

  if [[ $REPO_NAME == "deployer" ]]; then
    pull-tag-push-local
    return 0
  fi

  if [[ -f $ENTRYPOINT_FILE ]]; then
    source $ENTRYPOINT_FILE
  fi

  if [[ -f $COMPOSE_FILE ]]; then
    cd $REPO_PATH
    echo "$PREFIX Logging into local registry"
    docker login $SWARMLET_REGISTRY \
      -u $SWARMLET_REGISTRY_USER \
      -p $SWARMLET_REGISTRY_PASSWORD

    echo "$PREFIX Building $REPO_NAME"
    docker-compose build --parallel

    echo "$PREFIX Pushing $REPO_NAME"
    docker-compose push

    echo "$PREFIX Deploying $REPO_NAME"
    docker stack deploy --compose-file $COMPOSE_FILE $REPO_NAME

    HOSTS=$(docker-compose config | grep -o "Host:.*")
    DOMAINS="${HOSTS//Host:/}"
    PROTOCOL=https # todo

    echo "$FPREFIX Stack deployed:"
    for DOMAIN in ${DOMAINS[@]}; do echo "[$REPO_NAME] — $PROTOCOL://$DOMAIN"; done
    echo
  else
    echo "$PREFIX No docker-compose.yml found, exiting"
    exit 1
  fi
}

pull-tag-push-local() {
  echo "$PREFIX Logging into local registry"
  docker login $SWARMLET_REGISTRY \
    -u $SWARMLET_REGISTRY_USER \
    -p $SWARMLET_REGISTRY_PASSWORD

  echo "$PREFIX Pull, tag and push"
  docker pull swarmlet/deployer:test
  docker tag swarmlet/deployer:test $SWARMLET_REGISTRY/v2/deployer:latest
  docker push $SWARMLET_REGISTRY/v2/deployer:latest
}

main "$@"
