#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

ls -al /
cat /swarmlet-config
for f in /run/secrets/*; do echo $f; cat $f; done

printenv

main() {
  # declare cmd="deploy"
  # [[ "$1" == "$cmd" ]] && shift 1

  # docker container exec $(docker ps --filter name=$SERVICE -q) cat /my-config

  sleep 60

  date
  ls -al /
  cat /swarmlet-config
  for f in /run/secrets/*; do echo $f; cat $f; done

  main
}

main "$@"
