#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

FPREFIX="=====>"
PREFIX="----->"
INDENT="      "

NAME=$(basename $PWD)

main() {
  echo "$FPREFIX Running $NAME entrypoint script"
  echo "$PREFIX Arguments: $@"
  # echo "$PREFIX Environment:"; printenv

  echo "$PREFIX Environment variables from .env file"
  echo "$INDENT DOMAIN=$DOMAIN"
  echo "$INDENT MY_ENV_VAR=$MY_ENV_VAR"
  echo "$INDENT MY_ENV_VAR_UPPERCASE=$MY_ENV_VAR_UPPERCASE"
}

main "$@"
