#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

FPREFIX="=====>"
PREFIX="----->"
INDENT="      "

NAME=$(basename $PWD)

main() {
  echo "$FPREFIX Running $NAME entrypoint script"
}

main "$@"
