#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

ROOT_DIR=$(dirname "$0")
SUBCOMMAND="$ROOT_DIR/subcommands/$1"

set -o allexport
source "$ROOT_DIR/config"
source "$ROOT_DIR/functions"
set +o allexport

if [[ -f "$SUBCOMMAND" ]]; then $SUBCOMMAND "$@"; else
  echo "$PREFIX Unknown command: $1"
  echo "$INDENT This command might not be implemented yet"
  echo "$PREFIX Executing: swarmlet $@"
  "$@"
fi
