#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

ROOT_DIR=$(dirname "$0")
SUBCOMMANDS="$ROOT_DIR/subcommands"

set -o allexport
source "$ROOT_DIR/config"
source "$ROOT_DIR/functions"
set +o allexport

COMMAND="$1"

case $COMMAND in
  init) "$SUBCOMMANDS/init" "$@" ;;

  repo:create) "$SUBCOMMANDS/repo-create" "$@" ;;
  repo:remove) "$SUBCOMMANDS/repo-remove" "$@" ;;
  repo:list|repo:ls) "$SUBCOMMANDS/repo-list" "$@" ;;
  
  stack:build) "$SUBCOMMANDS/stack-build" "$@" ;;
  stack:deploy) "$SUBCOMMANDS/stack-deploy" "$@" ;;
  stack:list|stack:ls) "$SUBCOMMANDS/stack-list" "$@" ;;

  *) echo "$PREFIX Unknown command $COMMAND"; exit 1 ;;
esac
