#!/usr/bin/env bash

# --------------------
# config: swarmlet-env
# --------------------

# Swarmlet configuration and secrets
{{ secret "swarmlet-user-env" }}
{{ config "swarmlet-core-env" }}

# SWARMLET_USER={{ secret "swarmlet-user" }}
# SWARMLET_USER_ROOT={{ secret "swarmlet-user-root" }}
# SWARMLET_REGISTRY_USER={{ secret "swarmlet-registry-user" }}
# SWARMLET_REGISTRY_PASSWORD={{ secret "swarmlet-registry-password" }}
