#!/usr/bin/env bash
# shellcheck disable=SC2034

# ----------------------------
# config: swarmlet-core-config
# ----------------------------
# Docker config file

# Docker settings
DOCKER_SOCKET="/var/run/docker.sock"

# Swarmlet settings
SWARMLET_ROOT="/opt/swarmlet"
SWARMLET_LIB="$SWARMLET_ROOT/src/lib"
SWARMLET_CONSTANTS="$SWARMLET_ROOT/src/constants"
SWARMLET_CONFIG="$SWARMLET_ROOT/src/config"
SWARMLET_HOOKS="$SWARMLET_ROOT/src/hooks"
SWARMLET_MODULES_ROOT="$SWARMLET_ROOT/modules"
SWARMLET_FUNCTIONS="$SWARMLET_LIB/functions"
SWARMLET_REGISTRY="localhost:5000/v2"
SWARMLET_NETWORK="swarmlet-network"

# Git user settings
GIT_USER="git"
GIT_DATA="git-data"
GIT_USER_ROOT="/home/$GIT_USER"
GIT_REPO_ROOT="/var/repo"

# Traefik settings
TRAEFIK_NETWORK="traefik-public"
TRAEFIK_CERTS="/mnt/gfs/traefik"

# Ansible settings
ANSIBLE_HOSTS_FILE="/etc/ansible/hosts"

# Let's Encrypt CA servers
CA_PROD="https://acme-v02.api.letsencrypt.org/directory"
CA_TEST="https://acme-staging-v02.api.letsencrypt.org/directory"

# SSH settings for the git user
SSH_COMMAND="command=\"$SWARMLET_LIB/sshcommand $GIT_REPO_ROOT $SWARMLET_HOOKS\""
SSH_OPTIONS="no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty,$SSH_COMMAND"
