#!/usr/bin/env bash

# ----------------------------
# config: swarmlet-core-config
# ----------------------------
# Docker config file

# Run the following command if you update this file after installation:
### TODO: swarmlet config update swarmlet-core-config

SWARMLET_ROOT="/opt/swarmlet"
SWARMLET_LIB="$SWARMLET_ROOT/src/lib"
SWARMLET_CONSTANTS="$SWARMLET_ROOT/src/constants"
SWARMLET_CONFIG="$SWARMLET_ROOT/src/config"
SWARMLET_HOOKS="$SWARMLET_ROOT/src/hooks"
SWARMLET_MODULES_ROOT="$SWARMLET_ROOT/modules"
SWARMLET_FUNCTIONS="$SWARMLET_LIB/functions"
SWARMLET_REGISTRY="localhost:5000/v2"
SWARMLET_NETWORK="swarmlet-network"

GIT_USER="git"
GIT_DATA="git-data"
GIT_USER_ROOT="/home/$GIT_USER"
GIT_REPO_ROOT="/var/repo"

TRAEFIK_NETWORK=traefik-public
DOCKER_SOCKET="/var/run/docker.sock"

SSH_COMMAND="command=\"$SWARMLET_LIB/sshcommand $GIT_REPO_ROOT $SWARMLET_HOOKS\""
SSH_OPTIONS="no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty,$SSH_COMMAND"
