#!/usr/bin/env bash

REPO_ROOT="$1"
SWARMLET_HOOKS="$2"
REPO_NAME=$(echo $SSH_ORIGINAL_COMMAND | awk '{print $2}' | tr -d "'")
REPO_PATH="$GIT_REPO_ROOT/$REPO_NAME.git"

if [ ! -d $REPO_PATH ]; then
  git init --bare $REPO_PATH 1>&2
  cp -R $SWARMLET_HOOKS/* $REPO_PATH/hooks/
  chown -R $USER:$USER $REPO_PATH
fi

cd $GIT_REPO_ROOT && git-shell -c "$SSH_ORIGINAL_COMMAND"
