---
name: Kitchen

on:
  - push
  - pull_request

jobs:
  kitchen:
    # VirtualBox only runs on MacOS
    # See: https://github.com/actions/virtual-environments/issues/433
    # And: https://github.com/actions/virtual-environments/issues/183
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        instance:
          - debian-buster
          - ubuntu-focal

    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v2'

      - name: 'Set up Bundler cache'
        uses: 'actions/cache@v1'
        with:
          path: 'vendor/bundle'
          key: "${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}"
          restore-keys: "${{ runner.os }}-gems-"

      - name: 'Run Bundler'
        run: |
          ruby --version
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: 'Install Vagrant plugin'
        run: 'vagrant plugin install vagrant-vbguest'

      - name: 'Run Test Kitchen'
        run: 'bin/kitchen verify ${{ matrix.instance }}'
