#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

deploy() {
  declare cmd="deploy"
  [[ "$1" == "$cmd" ]] && shift 1

  REPO_PATH=$1

  # Wait for deployer to start
  while ! $(swarmlet is-service-healthy deployer_agent); do sleep 1; done
  DEPLOYER_AGENT=$(docker ps --filter name=deployer_agent -q)

  docker container exec $DEPLOYER_AGENT /entrypoint deploy $REPO_PATH
}

"$@"
