#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

deploy() {
  declare cmd="deploy"
  [[ "$1" == "$cmd" ]] && shift 1

  REPO_PATH=$1

  docker run --rm \
    --network $SWARMLET_NETWORK \
    -v $DOCKER_SOCKET:$DOCKER_SOCKET \
    -v $REPO_PATH:$REPO_PATH \
    $SWARMLET_REGISTRY/deployer \
    deploy $REPO_PATH
}

"$@"
