#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

is-service-healthy() {
  SERVICE="$1"
  CONTAINER_ID=$(docker-compose ps -q $SERVICE)
  HEALTH_STATUS=$(docker inspect -f "{{.State.Health.Status}}" $CONTAINER_ID)

  if [[ "$HEALTH_STATUS" == "healthy" ]];
    then return 0
    else return 1
  fi
}

deploy() {
  declare cmd="deploy"
  [[ "$1" == "$cmd" ]] && shift 1

  REPO_PATH=$1

  # Wait for deployer to start
  while ! is-service-healthy deployer_agent; do sleep 1; done
  DEPLOYER_AGENT=$(docker ps --filter name=deployer_agent -q)

  docker container exec $DEPLOYER_AGENT /entrypoint deploy $REPO_PATH
}

"$@"
