#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

init() {
  declare cmd="init"
  [[ "$1" == "$cmd" ]] && shift 1

  init-"$@"
}

init-interactive() {
  echo "$PREFIX Starting interactive installation"

  # Installation wizard dialogs
  swarmlet dialog welcome
  swarmlet dialog auth-info
  SWARMLET_USERNAME=$(swarmlet dialog set-username)
  SWARMLET_PASSWORD=$(swarmlet dialog set-password)
  SSH_AUTHORIZED_KEYS=$(swarmlet dialog set-ssh-authorized-keys)
  NEW_HOSTNAME=$(swarmlet dialog set-hostname)
  ROOT_DOMAIN=$(swarmlet dialog domain-config)
  INSTALL_MODULES=$(swarmlet dialog install-modules)
  CREATE_SWAP=$(swarmlet dialog add-swap)
  INSTALL_ZSH=$(swarmlet dialog install-zsh)
  # swarmlet dialog are-you-sure

  echo "$FPREFIX Wizard complete"
  echo "$PREFIX Setting up"
  # TODO: fix
  # install-dependencies "${SWARMLET_DEPENDENCIES[@]}" "$SWARMLET_DEPENDENCIES" $SWARMLET_DEPENDENCIES
  SWARMLET_DEPENDENCIES=(acl curl apache2-utils moreutils wget)

  update-package-cache
  notify-package-updates-available
  set-hostname $NEW_HOSTNAME $ROOT_DOMAIN
  $SUDO apt-get install -y -qq "${SWARMLET_DEPENDENCIES[@]}" &>/dev/null
  $INSTALL_DOCKER && install-docker
  $CREATE_SWAP && create-swap
  $INSTALL_ZSH && install-zsh

  echo "$PREFIX Setting up the git user"
  adduser $GIT_USER --disabled-password --gecos --quiet
  usermod -aG docker $GIT_USER
  mkdir -p $GIT_REPO_ROOT $GIT_USER_ROOT/.ssh
  setfacl -m u:$GIT_USER:rwx $GIT_REPO_ROOT

  echo "$PREFIX Configuring git SSH options"
  cat "$SSH_AUTHORIZED_KEYS" | ts "$SSH_OPTIONS" > $GIT_USER_ROOT/.ssh/authorized_keys
  chmod 700 $GIT_USER_ROOT/.ssh
  chmod 600 $GIT_USER_ROOT/.ssh/authorized_keys
  chown -R $GIT_USER:$GIT_USER $GIT_USER_ROOT/.ssh

  echo "$PREFIX Checking Docker status"
  if check-docker;
    then echo "Docker is running"; docker --version
    else echo "Docker is not running, exiting"; exit 1
  fi

  NODE_IP=$(hostname -I | awk '{print $1}')
  ADVERTISE_ADDR="$NODE_IP:2377"

  echo "$PREFIX Node IP address: $NODE_IP"
  echo "$PREFIX Initializing node as swarm manager"
  if check-swarm; then
    docker swarm init --advertise-addr $ADVERTISE_ADDR 2>&1 | head -n 1 && true
  fi

  echo "$PREFIX Creating secrets"
  cat << EOM | docker secret create swarmlet-user-secrets -
# User-defined secret environment variables
SWARMLET_USERNAME=$SWARMLET_USERNAME
SWARMLET_PASSWORD=$SWARMLET_PASSWORD
SWARMLET_REGISTRY_USERNAME=$SWARMLET_USERNAME
SWARMLET_REGISTRY_PASSWORD=$SWARMLET_PASSWORD
EOM

  echo "$PREFIX Creating configs"
  docker config create swarmlet-core-config $SWARMLET_CONSTANTS
  cat << EOM | docker config create --template-driver golang swarmlet-user-config -
# User-defined config environment variables
SSH_AUTHORIZED_KEYS=$SSH_AUTHORIZED_KEYS
NEW_HOSTNAME=$NEW_HOSTNAME
ROOT_DOMAIN=$ROOT_DOMAIN
INSTALL_MODULES=$INSTALL_MODULES
CREATE_SWAP=$CREATE_SWAP
INSTALL_ZSH=$INSTALL_ZSH

# Inject Swarmlet config environment variables
{{ config "swarmlet-core-config" }}
EOM

  echo "$PREFIX Creating networks"
  if [[ ! "$(docker network ls | grep $SWARMLET_NETWORK)" ]]; then
    docker network create \
      --attachable \
      --driver $SWARMLET_NETWORK_DRIVER \
      $SWARMLET_NETWORK
  else
    echo "$PREFIX $SWARMLET_NETWORK network already exists"
  fi

  if [[ ! "$(docker network ls | grep $TRAEFIK_NETWORK)" ]]; then
    docker network create \
      --attachable \
      --driver=overlay \
      $TRAEFIK_NETWORK
  else
    echo "$PREFIX $TRAEFIK_NETWORK network already exists"
  fi

  echo "$PREFIX Creating volumes"
  docker volume create \
    --driver "local" \
    -o o=bind \
    -o type=none \
    -o device=$GIT_USER_ROOT \
    git-data

  echo "$PREFIX Starting core modules"
  swarmlet stack start "core/registry" $SWARMLET_MODULES_ROOT
  swarmlet stack build "core/deployer" $SWARMLET_MODULES_ROOT

  SWARMLET_MODULES=(
    $(ls $SWARMLET_MODULES_ROOT/core | xargs -n1 echo core/ | sed 's/ //')
    $(echo "${INSTALL_MODULES[@]}" | xargs -n1 echo recommends/ | sed 's/ //')
  )

  for MODULE in ${SWARMLET_MODULES[@]}; do
    echo "$PREFIX Installing $MODULE"
    swarmlet repo create $(basename $MODULE) >/dev/null
    git-local-push $SWARMLET_MODULES_ROOT/$MODULE >/dev/null
  done
}

init-noninteractive() {
  echo "$PREFIX Starting noninteractive installation"
  echo "$PREFIX Setting up the git user"
  adduser $GIT_USER --disabled-password --gecos --quiet
  usermod -aG docker $GIT_USER
  mkdir -p $GIT_REPO_ROOT $GIT_USER_ROOT/.ssh
  setfacl -m u:$GIT_USER:rwx $GIT_REPO_ROOT

  echo "$PREFIX Configuring git SSH options"
  cat "$SSH_AUTHORIZED_KEYS" | ts "$SSH_OPTIONS" > $GIT_USER_ROOT/.ssh/authorized_keys
  chmod 700 $GIT_USER_ROOT/.ssh
  chmod 600 $GIT_USER_ROOT/.ssh/authorized_keys
  chown -R $GIT_USER:$GIT_USER $GIT_USER_ROOT/.ssh

  if [[ $CREATE_SWAP == "true" ]]; then
    echo "$PREFIX Creating 1GB of swap space"
    create-swap 1G /swapfile
  fi

  echo "$PREFIX Checking Docker status"
  if check-docker;
    then echo "Docker is running"; docker --version
    else echo "Docker is not running, exiting"; exit 1
  fi

  NODE_IP=$(hostname -I | awk '{print $1}')
  ADVERTISE_ADDR="$NODE_IP:2377"

  echo "$PREFIX Node IP address: $NODE_IP"
  echo "$PREFIX Initializing node as swarm manager"
  if [[ check-swarm ]]; then
    docker swarm init --advertise-addr $ADVERTISE_ADDR 2>&1 | head -n 1 && true
  fi

  echo "$PREFIX Creating secrets"
  # TODO: get from user input or arguments
  swarmlet secret create swarmlet-user-env $SWARMLET_SECRETS

  echo "$PREFIX Creating configs"
  swarmlet config create swarmlet-core-env $SWARMLET_CONSTANTS
  swarmlet config create swarmlet-env $SWARMLET_CONFIG

  echo "$PREFIX Creating networks"
  if [[ ! "$(docker network ls | grep $SWARMLET_NETWORK)" ]]; then
    docker network create \
      --attachable \
      --driver $SWARMLET_NETWORK_DRIVER \
      $SWARMLET_NETWORK
  else
    echo "$PREFIX $SWARMLET_NETWORK network exists"
  fi

  echo "$PREFIX Creating volumes"
  docker volume create \
    --driver "local" \
    -o o=bind \
    -o type=none \
    -o device=$GIT_USER_ROOT \
    git-data

  echo "$PREFIX Starting core modules"
  swarmlet stack start "core/registry" $SWARMLET_MODULES_ROOT
  swarmlet stack build "core/deployer" $SWARMLET_MODULES_ROOT

  SWARMLET_MODULES=(
    $(ls $SWARMLET_MODULES_ROOT/core | xargs -n1 echo core/ | sed 's/ //')
    $(echo "${INSTALL_MODULES[@]}" | xargs -n1 echo recommends/ | sed 's/ //')
  )

  for MODULE in ${SWARMLET_MODULES[@]}; do
    echo "$PREFIX Installing $MODULE"
    swarmlet repo create $(basename $MODULE) >/dev/null
    git-local-push $SWARMLET_MODULES_ROOT/$MODULE >/dev/null
  done
}

"$@"
