#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

logs() {
  declare cmd="logs"
  [[ "$1" == "$cmd" ]] && shift 1

  SERVICE=$1
  FOLLOW=$2

  docker service logs $SERVICE $FOLLOW
}

"$@"
