#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

cmd-minimal-init() {
  declare cmd="minimal-init"
  [[ "$1" == "$cmd" ]] && shift 1

  echo "$PREFIX Setting up the git user"
  adduser $USERNAME --disabled-password --gecos --quiet
  usermod -aG docker $USERNAME
  mkdir -p $REPO_ROOT $USER_ROOT/.ssh
  cat /root/.ssh/authorized_keys | ts "$SSH_OPTIONS" > $USER_ROOT/.ssh/authorized_keys
  chmod 700 $USER_ROOT/.ssh
  chmod 600 $USER_ROOT/.ssh/authorized_keys
  chown -R $USERNAME:$USERNAME $USER_ROOT/.ssh
  setfacl -m u:$USERNAME:rwx $REPO_ROOT

  docker network create \
    --attachable \
    --driver $SWARMLET_NETWORK_DRIVER \
    $SWARMLET_NETWORK_NAME

  echo "$PREFIX Creating volumes"
  docker volume create \
    --driver "local" \
    -o o=bind \
    -o type=none \
    -o device=$USER_ROOT \
    git-data

  pushd $SWARMLET_SERVICES_ROOT/registry >/dev/null
  docker-compose up -d
  popd >/dev/null
}

cmd-minimal-init "$@"
