#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

node() {
  declare cmd="node"
  [[ "$1" == "$cmd" ]] && shift 1

  node-"$@"
}

node-join() {
  declare cmd="join"
  [[ "$1" == "$cmd" ]] && shift 1

  ROLE=$1
  NODE_IP=$2


}

node-remove() {
  declare cmd="remove"
  [[ "$1" == "$cmd" ]] && shift 1

  NODE_IP=$1

  
}

"$@"
