#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

cmd-stack-stop() {
  declare cmd="stack:stop"
  [[ "$1" == "$cmd" ]] && shift 1

  STACK_NAME="$1"

  echo "$PREFIX Stopping stack"
  # if stack is running stop
  # if stack is not running, display message
  pushd $STACK_NAME/registry >/dev/null
  docker-compose down
  popd >/dev/null
}

cmd-stack-stop "$@"
