#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

cmd-stack-start() {
  declare cmd="stack:start"
  [[ "$1" == "$cmd" ]] && shift 1

  STACK_NAME="$1"

  echo "$PREFIX Starting stack"
  # if stack is running, update stack
  # if stack is not running, start stack
  pushd $STACK_NAME/registry >/dev/null
  docker-compose up -d
  popd >/dev/null
}

cmd-stack-start "$@"
