#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

cmd-stack-deploy() {
  declare cmd="stack:deploy"
  [[ "$1" == "$cmd" ]] && shift 1

  STACK_NAME="$1"
  STACK_ROOT="$USER_ROOT/$STACK_NAME"
  COMPOSE_FILE="$STACK_ROOT/docker-compose.yml"

  pushd $STACK_ROOT >/dev/null
  echo "$PREFIX Deploying $STACK_NAME"
  echo $STACK_ROOT

  docker stack deploy --compose-file $COMPOSE_FILE $STACK_NAME

  popd >/dev/null
}

cmd-stack-deploy "$@"
