#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

stack() {
  declare cmd="stack"
  [[ "$1" == "$cmd" ]] && shift 1

  stack-"$@"
}

stack-build() {
  declare cmd="build"
  [[ "$1" == "$cmd" ]] && shift 1

  
}

stack-deploy() {
  declare cmd="deploy"
  [[ "$1" == "$cmd" ]] && shift 1

  
}

stack-list() {
  declare cmd="list"
  [[ "$1" == "$cmd" ]] && shift 1

  
}

stack-start() {
  declare cmd="start"
  [[ "$1" == "$cmd" ]] && shift 1

  
}

stack-stop() {
  declare cmd="stop"
  [[ "$1" == "$cmd" ]] && shift 1

  
}

"$@"
