#!/usr/bin/env bash

set -eo pipefail; [[ $DEBUG ]] && set -x

uninstall() {
  declare cmd="uninstall"
  [[ "$1" == "$cmd" ]] && shift 1

  rm /usr/local/sbin/swarmlet
  rm -rf $SWARMLET_ROOT $REPO_ROOT $USER_ROOT
  deluser $USERNAME
}

"$@"
